#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


######
# POWERLEVER OPTS
######

POWERLEVEL9K_MODE="nerdfont-complete"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export DEFAULT_USER="mateusz"
POWERLEVEL9K_DIR_PATH_SEPARATOR=$'\uE0B1'
POWERLEVEL9K_HOME_SUB_ICON=$'\uF015'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"
POWERLEVEL9K_TIME_BACKGROUND='255'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time)
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_STATUS_VERBOSE=true

######
# OTHERS
######

alias prezto='cd ~/.zprezto/ ; git pull && git submodule update --init --recursive'

function precmd() {
  if command git rev-parse --git-dir > /dev/null 2>&1; then
    tab_label=$(git rev-parse --show-toplevel | awk -F\/ '{print "[git] " $NF}')
  else
    tab_label=${PWD/${HOME}/\~}
  fi
  echo -ne "\e]1;${tab_label: -24}\a"
}
eval $(thefuck --alias)

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi