#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

eval `keychain --eval id_rsa`

######
# POWERLEVER OPTS
######

POWERLEVEL9K_MODE="nerdfont-complete"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export DEFAULT_USER="mateusz"
POWERLEVEL9K_DIR_PATH_SEPARATOR=$'\uE0B1'
POWERLEVEL9K_HOME_SUB_ICON=$'\uF015'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"
POWERLEVEL9K_TIME_BACKGROUND='255'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable aws vcs)
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_STATUS_VERBOSE=true

######
# OTHERS
######
# aliases
alias tb="nc termbin.com 9999"

# prezto
alias prezto='cd ~/.zprezto/ ; git pull upstream master && git submodule update --init --recursive'

# thefuck
eval $(thefuck --alias)

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
eval "$(jenv enable-plugin export)"

#nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# golang
export GOPATH=/mnt/c/Users/mateusz/code/go
export PATH="/usr/local/opt/go/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"

# exports
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/home/mbajorek/.local/bin:$PATH"

export GITHUB_ACCESS_TOKEN="<token>"
export GITHUB_TOKEN="<token>"

export DOCKER_HOST="tcp://localhost:2375"

# brew not found suggestions
if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi

# read .bash_profile as well
if [ -f ~/.bash_profile ] ; then
    . ~/.bash_profile
fi

precmd() {
  if command git rev-parse --git-dir > /dev/null 2>&1; then
    tab_label=$(git rev-parse --show-toplevel | awk -F\/ '{print "[git] " $NF}')
  else
    tab_label=${PWD/${HOME}/\~}
  fi
  echo -ne "\e]1;${tab_label: -24}\a"
}

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/mateusz/.sdkman"
[[ -s "/Users/mateusz/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/mateusz/.sdkman/bin/sdkman-init.sh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
